var PERMISSION_UPLOADIMAGE="uploadImage";
var PERMISSION_DELETEIMAGE="deleteImage";

module.exports ={
    PERMISSION_UPLOADIMAGE : PERMISSION_UPLOADIMAGE,
    PERMISSION_DELETEIMAGE: PERMISSION_DELETEIMAGE
}